### ISSUE TITLE
Helper method for closing browser contexts

### ISSUE THREAD

**Issue by inancgumus** [grafana/xk6-browser#1041]
### What?

Provide a `browser.closeContext` method to close the current `BrowserContext`.

### Why?

* [Users might need][1] to close a `BrowserContext` when they run multiple test functions.
* Calling `browser.context().close();` after each test run is a bit cumbersome, [similar to a train-wreck anti-pattern](https://wiki.c2.com/?TrainWreck).

[1]: https://community.grafana.com/t/existing-browser-context-must-be-closed-before-creating-a-new-one-k6-0-46/102457/9

### How?

1. Add a new `CloseContext` method in the `api` and `common` packages.
2. Call the `BrowserContext.Context()`'s `Close` method.

### Tasks

```[tasklist]
### Tasks
- [x] PR: https://github.com/grafana/xk6-browser/pull/1074
- [x] Docs PR: https://github.com/grafana/k6-docs/pull/1376
- [x] TypeScript Definitions PR: https://github.com/grafana/k6-DefinitelyTyped/pull/16
- [x] k6 release notes PR: https://github.com/grafana/k6/pull/3419
```
