### ISSUE TITLE
Make sure we adhere to the k6 options `DNS`, `Blacklist IPs`, `Block hostnames` and `Hosts`

### ISSUE THREAD

**Issue by robingustafsson** [grafana/xk6-browser#105]
Right now xk6-browser doesn't obey the following network related k6 options, but we should (if possible that is):

- [x] [DNS](https://k6.io/docs/using-k6/options/#dns) (N/A, see [comment](https://github.com/grafana/xk6-browser/issues/105#issuecomment-1022093138))
- [x] [Blacklist IPs](https://k6.io/docs/using-k6/options/#blacklist-ips) (PR #205)
- [x] [Block hostnames](https://k6.io/docs/using-k6/options/#block-hostnames) (PR #204)
- [x] [Hosts](https://k6.io/docs/using-k6/options/#hosts) (PR #207)

It should hopefully be possible by using the experimental [`Fetch`](https://chromedevtools.github.io/devtools-protocol/tot/Fetch/) CDP domain and intercepting requests and either aborting request with [`Fetch.failRequest(Network.ErrorReason.BlockedByClient)`](https://chromedevtools.github.io/devtools-protocol/tot/Fetch/#method-failRequest) or modifying the URL and then calling [`Fetch.continueRequest()`](https://chromedevtools.github.io/devtools-protocol/tot/Fetch/#method-continueRequest).

This is also very much related to [`BrowserContext.route()`](https://github.com/grafana/xk6-browser/issues/10) and [`BrowserContext.unroute()`](https://github.com/grafana/xk6-browser/issues/12) as they would also use the Fetch CDP domain APIs.

**Comment by imiric** [comment]
This seems to be possible by handling the `Fetch` events from Go. At least it looks supported by cdproto: https://pkg.go.dev/github.com/chromedp/cdproto/fetch
Here's an example of modifying a request: https://github.com/chromedp/chromedp/issues/805#issuecomment-829806460

Playwright and Puppeteer additionally expose this API to users, so requests can be intercepted from JS. See [this repo](https://github.com/subwaymatch/cdp-modify-response-example) for examples.
This isn't a requirement for this issue, and we won't be able to implement it without an event loop anyway, so we can postpone this for now. I'm just mentioning it as something we might want to eventually expose to JS as well.

I'll experiment with doing this from Go somewhere in `BrowserContext` most likely. :hamster:

**Comment by imiric** [comment]
@robingustafsson I'm working on a PoC for this feature, and noticed there's some previous work in this area:

https://github.com/grafana/xk6-browser/blob/9e0085ef4a1c6ec233e657248c921659b3c3e8d3/common/network_manager.go#L364-L378

https://github.com/grafana/xk6-browser/blob/9e0085ef4a1c6ec233e657248c921659b3c3e8d3/api/route.go#L25-L31

It appears to be half-baked though, as `Page.routes` is never appended to.

Can you comment on your initial design ideas for this? It seems like you wanted to expose it to JS in some way, and I'm wondering if I should continue on this path or if this can be scrapped.

**Comment by robingustafsson** [comment]
@imiric Feel free to scrap or re-use the code as you see fit. I ditched the effort early as it required too much time for what I had available at that point, and I didn't see it as a prio compared to other issues present then.

The interface is just following the Playwright API: https://playwright.dev/docs/api/class-route

**Comment by imiric** [comment]
@robingustafsson I'm wondering how the DNS options should be applied.

AFAICT there is no way for us to control the resolution logic with CDP at the level that we do in k6. The only thing users have access to is clearing the resolver cache via `chrome://net-internals/#dns`, or [passing `--host-resolver-rules`](https://datacadamia.com/web/browser/chrome#dns_resolver) to remap hosts (the same thing could presumably be done with `/etc/hosts`, though [there are some old reports that it's unreliable](https://askubuntu.com/a/852596)). The arg can already be passed via `launcher.launch()`, but this is not something the k6 DNS option is for, so it doesn't really apply for this use case.

Additionally, this would be only for Chrome, as Firefox behaves differently, so I'm not sure we should bother if it can't be done via CDP.

**Comment by imiric** [comment]
@robingustafsson With #207 this issue should be done. Let me know if there's anything pending.
