### ISSUE TITLE
Isolate browser contexts between iterations

### ISSUE THREAD

**Issue by inancgumus** [grafana/xk6-browser#1112]
### What?

Separate browser contexts to make each iteration focus solely on its pages rather than those created by other iterations.

### Why?

While investigating #971 and other relevant issues, it became apparent that the issue wasn't about bug fixing but more about the general workings of the module that stagnated the whole process down to its knees. Here's a solution.

Isolating browser contexts might provide:
- Efficiency (10X)
- Better debugging (less log noise)
- Possibly less deadlocks

### More why:

- Each iteration has a single browser context.
- However, iterations track the pages of other iterations besides their own. This causes them to deadlock when the browser specs are low and there are many VUs.
- Isolating browser contexts for each iteration can allow other iterations to deal only with their own pages.
- By isolating browser contexts, we prevent VUs from tracking pages outside their iterations, reducing timeouts and improving efficiency.

### Additional info

On the remote, with 1K iterations, we see that:
- VUs spend a lot of time tracking the pages of other iterations.
- Most of their time goes to tracking instead of doing their own work.
- While they're tracking other iterations, navigations continue, and timeouts occur. One of them is `err:timed out .. category=Browser:newPageInContext`.-
- Almost whenever there are a lot of iterations. we can observe this locally, too.

### Tasks

```[tasklist]
### Tasks
- [x] Investigate `setAutoAttach`.
- [x] Investigate: Internally track browser contexts and refuse to attach to pages of other iterations.
- [x] Run many remote tests to verify the solution.
- [x] Polish.
- [x] Prepare a report.
- [ ] https://github.com/grafana/xk6-browser/pull/1219
- [ ] https://github.com/grafana/k6/pull/3624
- [x] Update the k6 release notes for: #445, #861, #966, #970, #971, #973, #1112
```

### Related PR(s)/Issue(s)

#848 ignored the pages created by the browser contexts of other VUs/instances.

There, we found that:
- Each iteration (so a VU) tracks the pages created by other iterations.
- Pages aren't confined to their initiating browser context (and VUs), leading to VUs tracking unrelated pages.

Others: #971, #966, #970, #861, #445

### Issues will be closed by this issue (possibly 🤞)

#971, #966, #973, and #986.
