### ISSUE TITLE
Browser: Runtime stability

### ISSUE THREAD

**Issue by inancgumus** [grafana/xk6-browser#1138]
### What?

Stabilize the browser module in runtime.

### Why?

To provide a better experience and trust to run browser tests.

### Tasks

```[tasklist]
### Primary issues
- [ ] grafana/xk6-browser#1072
- [ ] grafana/xk6-browser#1112
- [ ] grafana/xk6-browser#971
- [ ] grafana/xk6-browser#1066
- [ ] https://github.com/grafana/xk6-browser/issues/987
```

Several other issues might be related to the primary deadlock issues above.

```[tasklist]
### Related issues
- [ ] grafana/xk6-browser#966
- [ ] grafana/xk6-browser#1048
- [ ] grafana/xk6-browser#973
- [ ] grafana/xk6-browser#986
- [ ] grafana/xk6-browser#445
- [ ] grafana/xk6-browser#557
- [ ] grafana/xk6-browser#237
```
