### ISSUE TITLE
Goja runtime shouldn't be accessed while parsing options in async APIs

### ISSUE THREAD

**Issue by ankur22** [grafana/xk6-browser#1162]
# What

We must not work with the goja runtime when the browser module is running a promisified API call off the event loop i.e. on a new goroutine. All promisified APIs in the browser run in a new goroutine. A concrete example of such a case is with [page.goto](https://github.com/grafana/xk6-browser/blob/5f754c2c2252896016fd77d1fd3234a795049a0e/common/frame.go#L954-L956) where it is parsing the goja values in the new goroutine, which should be moved to the mapping layer.

This issue only deals with the refactoring of the option and argument parsing, https://github.com/grafana/xk6-browser/issues/1182 deals with the inner goja usage.

# Why

The goja runtime is not thread safe and should only be accessed when running on the event loop. If this is not adhered to, it can cause panics during runtime.

# How

The following is the list of all async/promisified APIs, check each one and ensure that the goja runtime is only accessed in the event loop thread and not in the new go routine.

```[tasklist]
### Tasks
- [x] https://github.com/grafana/xk6-browser/pull/1164
- [ ] https://github.com/grafana/xk6-browser/issues/1169
- [ ] https://github.com/grafana/xk6-browser/issues/1172
- [ ] https://github.com/grafana/xk6-browser/issues/1174
- [ ] https://github.com/grafana/xk6-browser/issues/1176
- [ ] https://github.com/grafana/xk6-browser/issues/1177
- [ ] https://github.com/grafana/xk6-browser/issues/1180
- [ ] https://github.com/grafana/xk6-browser/issues/1181
- [ ] https://github.com/grafana/xk6-browser/issues/1184
- [ ] https://github.com/grafana/xk6-browser/issues/1185
- [ ] https://github.com/grafana/xk6-browser/issues/1187
- [x] https://github.com/grafana/xk6-browser/issues/1178
- [x] Fix `browserContext.setExtraHTTPHeaders` (unimplemented method)
- [x] Add fixes to release notes: https://github.com/grafana/k6/pull/3578
```

# Note

**Comment by inancgumus** [comment]
Should we close this one? @ankur22
