### ISSUE TITLE
Remove Goja from Execution Context Eval

### ISSUE THREAD

**Issue by ankur22** [grafana/xk6-browser#1182]
# What

`ExecutionContext.Eval` is at the heart of the module. Removing its Goja dependency will tremendously detach goja from most of the business logic. [executionContext.eval](https://github.com/grafana/xk6-browser/blob/main/common/execution_context.go#L155-L157) takes a slice argument, which can be of any type, including `goja.Value`. Find a way to enforce a change where the slice must be anything BUT a `goja.Value`.

# Why

- Improved stability: Enable avoiding working with the non-thread safe Goja from multiple goroutines.
- Productivity: Business logic can use native Go constructs. Code is simpler and easy to reason about.
- Testability: Testing the business logic becomes straightforward.

# How

- Remove `goja` from `Eval` and all related methods.
- Ensure that none of the methods in the module passes goja values to `Eval` and friends.
- Add assertions and keep them there for a few cycles.

# Related

#1162

```[tasklist]
### Tasks
- [ ] https://github.com/grafana/xk6-browser/issues/1170
- [ ] https://github.com/grafana/xk6-browser/pull/1189
- [ ] https://github.com/grafana/xk6-browser/pull/1191
- [ ] https://github.com/grafana/xk6-browser/pull/1193
- [ ] https://github.com/grafana/xk6-browser/issues/1168
- [ ] https://github.com/grafana/xk6-browser/pull/1190
- [x] What about the other APIs that still use goja? None of them escape Goja as it seems. (see https://github.com/grafana/xk6-browser/issues/1064)
- [x] Release notes: https://github.com/grafana/k6/pull/3578
```

**Comment by inancgumus** [comment]
Wrapping up this one 🎉
