### ISSUE TITLE
`frame.waitForSelector` waits indefinitely

### ISSUE THREAD

**Issue by ankur22** [grafana/xk6-browser#1252]
## What

When running the script that is outlined in this [community support forum](https://community.grafana.com/t/getting-a-panic-error-in-test-after-clicking-place-order-button/115572) the `const field1 = frame.waitForSelector("//input[placeholder='Card Number']");` line seems to hang indefinitely. 
```[tasklist]
### Tasks
- [ ] https://github.com/grafana/xk6-browser/pull/1254
- [ ] https://github.com/grafana/xk6-browser/pull/1261
- [x] Release notes: https://github.com/grafana/k6/commit/0d27f9bd711aadc4a71b50d4d4d7ab5fbe1906e3
```
