### ISSUE TITLE
De-sobekify `BrowserContext` methods

### ISSUE THREAD

**Issue by inancgumus** [grafana/xk6-browser#1270]
See grafana/xk6-browser#1064.

```[tasklist]
### Tasks
- [ ] grafana/xk6-browser#1504
- [ ] grafana/xk6-browser#1507
- [ ] grafana/xk6-browser#1510
- [ ] grafana/xk6-browser#1511
- [ ] https://github.com/grafana/xk6-browser/pull/1512
- [ ] https://github.com/grafana/xk6-browser/pull/1513
- [ ] https://github.com/grafana/xk6-browser/pull/1518
- [ ] grafana/xk6-browser#1519
- [ ] https://github.com/grafana/xk6-browser/pull/1520
- [ ] https://github.com/grafana/xk6-browser/pull/1521
- [ ] https://github.com/grafana/xk6-browser/pull/1526
- [ ] https://github.com/grafana/xk6-browser/pull/1527
- [ ] Add release notes
```
