### ISSUE TITLE
`page.on('download')`

### ISSUE THREAD

**Issue by inancgumus** [grafana/xk6-browser#1289]
### What?

TBA

### Why?

TBA

### Tasks

```[tasklist]
### Tasks
- [ ] Research: `browser.on` generalization
- [ ] PR
- [ ] Docs PR
- [ ] TypeScript Definitions PR
- [ ] Update the k6 release notes
```

**Comment by inancgumus** [comment]
I did some research on this issue.

What we're looking for does not seem to be `page.on('download`)`, it's file choosers.

Playwright [does not support](https://playwright.dev/docs/api/class-filechooser) skipping file choosers, but Puppeter [does](https://pptr.dev/api/puppeteer.filechooser):

```javascript
const [fileChooser] = await Promise.all([
  page.waitForFileChooser(),
  page.click('#upload-file-button'), // some button that triggers file selection
]);
await fileChooser.cancel();
```

@ankur22 WDYT?

**Comment by ankur22** [comment]
Thanks for looking into to it 👍 

> What we're looking for does not seem to be `page.on('download')`, it's file choosers.

What's the reason for not going with `page.on('download')`. With Playwright we can still [cancel downloads](https://playwright.dev/docs/api/class-download#download-cancel) with:

```js
page.on('download', data => {
    await data.cancel();
});
```

I'm happy with either solution, but why choose `fileChooser` over `page.on('download')`?

> Playwright [does not support](https://playwright.dev/docs/api/class-filechooser) skipping file choosers, but Puppeter [does](https://pptr.dev/api/puppeteer.filechooser):

Good spot, worth noting, thanks for that 👍

**Comment by ankur22** [comment]
I like this new proposal where we're working with an existing field on `browserContext` 🙏 

```js
const context = await browser.newContext({
    acceptDownloads: false,
});
```
