### ISSUE TITLE
Migrating to k6-core's linter

### ISSUE THREAD

**Issue by inancgumus** [grafana/xk6-browser#1292]
### What?

* k6-core and k6-browser linter configurations do not match.
* Use k6-core's version directly or use it as the base and extend it with k6-browser's additional rules.

### Why?

* To rely on a shared and reviewed configuration across teams.
* To prevent security issues like `setInputFiles`.

### How?

k6-core prefers to use the same rules used in the linter configuration to sync across the projects (or extensions in general). k6-core has created [a reusable workflow](https://github.com/grafana/k6-ci) that they've been using for other minor extensions, as well.  A concrete example is related to the `os` package [which is denied](https://github.com/grafana/k6/blob/master/.golangci.yml#L64) in the k6-core configuration.

They suggest k6-browser to use the entire workflow [here](https://github.com/grafana/xk6-grpc/blob/main/.github/workflows/all.yml#L12-L14) for example. Or, only [the linter configuration part](https://github.com/grafana/k6-ci/blob/883239d9b74eba603d530375685c55ec82621478/.github/workflows/all.yml#L45-L46).  They believe a better case would be the ability to merge two golangci configurations, but they don't find it as a solution at the moment.

### Tasks

```[tasklist]
### Tasks
- [ ] Work with the same linter + dependency job -- see [comment](https://github.com/grafana/xk6-browser/issues/1292#issuecomment-2092665993)
- [ ] Work with the same test jobs -- see [comment](https://github.com/grafana/xk6-browser/issues/1292#issuecomment-2092708331)
- [ ] Fix older lint issues
- [ ] Migrate fully to work with https://github.com/grafana/k6-ci
```

**Comment by inancgumus** [comment]
cc: @codebien

**Comment by ankur22** [comment]
@codebien @inancgumus I've taken a look at this for the browser project. I think this is a great idea. Unfortunately the browser codebase deviates quite a bit from the k6 codebase, and therefore the k6 linter rules point out many issues in the browser code base:

<details>
</details>

**Comment by ankur22** [comment]
@codebien @inancgumus apart from the lint, there are also the following jobs:

- `dependencies`
- `test-go-versions`
- `test-build`

`test-go-versions` isn't going to work with the browser codebase since we need to be able to add some env vars when running the test like we've done [here](https://github.com/grafana/xk6-browser/blob/main/.github/workflows/test.yml#L42). The possible solutions for this are:

1. Only work with the lint workflow for now, as long as we can resolve the issue detailed in this [comment](https://github.com/grafana/xk6-browser/issues/1292#issuecomment-2092665993).
2. Amend `test-go-versions` so that it accepts arguments.

WDYT?

**Comment by inancgumus** [comment]
@ankur22 @codebien 

> Add only-new-issues: true to the golangci-lint CI action after this [line](https://github.com/grafana/k6/blob/master/.github/actions/lint/action.yml#L31), which would allow all existing linter issues to exist, but lint new code changes.

+1 for this. Other than aligning codebases, the primary idea of merging linters is to prevent security issues. For now, I believe it's good enough to cover future code changes with the k6-core linter integration. We'll eventually get to work on fixing the remaining linter issues for the existing code in time (which doesn't have security issues).

> test-go-versions isn't going to work with the browser codebase since we need to be able to add some env vars when running the test like we've done [here](https://github.com/grafana/xk6-browser/blob/main/.github/workflows/test.yml#L42). The possible solutions for this are:
> 
> 1. Only work with the lint workflow for now, as long as we can resolve the issue detailed in this https://github.com/grafana/xk6-browser/issues/1292#issuecomment-2092665993.
> 2. Amend test-go-versions so that it accepts arguments.

I'm fine with the second option if @grafana/k6-core is also fine with it. If not, I think the first option is good enough.

**Comment by codebien** [comment]
>Add only-new-issues: true to the golangci-lint CI action after this [line](https://github.com/grafana/k6/blob/master/.github/actions/lint/action.yml#L31), which would allow all existing linter issues to exist, but lint new code changes.

This approach sounds the correct one for starting. :+1: 

In any case, you should review the current cases to check if we have some with high priority. Maybe, we have to allocate someone to support you on this review.

**Comment by ankur22** [comment]
> In any case, you should review the current cases to check if we have some with high priority. Maybe, we have to allocate someone from our team to support you on this review.

Agreed that the codebase should be audited by a k6-core team member. This is believe is the plan in any case before the browser module can be graduated out of experimental. For this issue, i believe it should be good enough to trust that all due diligence has been met so far, but with the belief that we will correctly align the codebase style and conform to the security standards ok k6, although we may need to make some exceptions for `os` package usage.

**Comment by ankur22** [comment]
1. The plan is to copy/use the lint file from [here](https://github.com/grafana/k6/blob/master/.github/actions/lint/action.yml) and use it in this project, and add `only-new-issues: true` to that file so that only future changes will be linted.
2. See if it's possible to amend `test-go-versions` so that it accepts arguments.

**Comment by mstoykov** [comment]
This is going to be really nice in order for us to be able to merge this repo into the k6 one 

https://github.com/grafana/k6/pull/4056

**Comment by inancgumus** [comment]
Yep, let's prioritize this.
