### ISSUE TITLE
Improve the `Tap` documentation

### ISSUE THREAD

**Issue by inancgumus** [grafana/xk6-browser#1293]
### What?

Improve the async `Tap` documentation by adding the missing docs.

### Why?

Some docs (listed in the tasks) are missing.

### Tasks

```[tasklist]
### Tasks
- [x] Update `touchscreen.tap` docs
- [x] Add `Frame.tap` docs
- [x] Add `ElementHandle.tap` docs
- [ ] grafana/k6-docs#1581
- [x] [Copy the changes into v0.51.0](https://github.com/grafana/k6-docs/tree/main/CONTRIBUTING#use-the-apply-patch-script)
- [x] Update v0.51.0 release notes for the updated docs
```

### Related PR(s)/Issue(s)

#1251
