### ISSUE TITLE
Migrate BrowserContext APIs to async

### ISSUE THREAD

**Issue by ankur22** [grafana/xk6-browser#1295]
```[tasklist]
### Tasks
- [ ] #1326
- [ ] #1327
- [ ] https://github.com/grafana/xk6-browser/pull/1328
- [ ] grafana/k6-docs#1590
- [ ] https://github.com/grafana/k6-DefinitelyTyped/pull/44
- [x] Add release notes
```

---

## What

Migrate the following APIs according to the How section in https://github.com/grafana/xk6-browser/issues/428:

| Class | Method | Current k6 Return | PW return |
| ---- | ---- | ---- | ---- |
|BrowserContext|addCookies|void|Promise<void>|
|BrowserContext|addInitScript|void|not found in Playwright|
|BrowserContext|browser|Browser|null\|Browser|
|BrowserContext|clearCookies|void|Promise<void>|
|BrowserContext|clearPermissions|void|Promise<void>|
|BrowserContext|close|void|Promise<void>|
|BrowserContext|cookies|Cookie[]|Promise<Array<Cookie>>|
|BrowserContext|grantPermissions|void|Promise<void>|
|BrowserContext|newPage|Page|Promise<Page>|
|BrowserContext|setGeolocation|void|Promise<void>|
|BrowserContext|setOffline|void|Promise<void>|

For details on the Why and How, check the overarching issue in https://github.com/grafana/xk6-browser/issues/428.
