### ISSUE TITLE
Migrate ElementHandle APIs to async

### ISSUE THREAD

**Issue by ankur22** [grafana/xk6-browser#1296]
```[tasklist]
### Tasks
- [ ] #1335
- [ ] https://github.com/grafana/xk6-browser/pull/1337
- [ ] #1370
- [ ] #1371
- [ ] grafana/k6-docs#1598
- [ ] https://github.com/grafana/k6-DefinitelyTyped/pull/49
- [ ] Add release notes
```

---

## What

Migrate the following APIs according to the How section in https://github.com/grafana/xk6-browser/issues/428:

| Class | Method | Current k6 Return | PW return |
| ---- | ---- | ---- | ---- |
|ElementHandle|$|ElementHandle\|null|Promise<ElementHandle<SVGElement\|HTMLElement>\|null>|
|ElementHandle|$$|ElementHandle[]|Promise<ElementHandle<SVGElement\|HTMLElement>[]>|
|ElementHandle|boundingBox|Rect|Promise<null\|{x:number;y:number;width:number;height:number;}>|
|ElementHandle|check|void|Promise<void>|
|ElementHandle|contentFrame|Frame|Promise<null\|Frame>|
|ElementHandle|dblclick|void|Promise<void>|
|ElementHandle|dispatchEvent|void|Promise<void>|
|ElementHandle|fill|void|Promise<void>|
|ElementHandle|focus|void|Promise<void>|
|ElementHandle|getAttribute|string\|null|Promise<null\|string>|
|ElementHandle|hover|void|Promise<void>|
|ElementHandle|innerHTML|string|Promise<string>|
|ElementHandle|innerText|string|Promise<string>|
|ElementHandle|inputValue|string|Promise<string>|
|ElementHandle|isChecked|boolean|Promise<boolean>|
|ElementHandle|isDisabled|boolean|Promise<boolean>|
|ElementHandle|isEditable|boolean|Promise<boolean>|
|ElementHandle|isEnabled|boolean|Promise<boolean>|
|ElementHandle|isHidden|boolean|Promise<boolean>|
|ElementHandle|isVisible|boolean|Promise<boolean>|
|ElementHandle|ownerFrame|Frame|Promise<null\|Frame>|
|ElementHandle|press|void|Promise<void>|
|ElementHandle|screenshot|ArrayBuffer|Promise<Buffer>|
|ElementHandle|scrollIntoViewIfNeeded|void|Promise<void>|
|ElementHandle|selectOption|string[]|Promise<Array<string>>|
|ElementHandle|selectText|void|Promise<void>|
|ElementHandle|setInputFiles|void|Promise<void>|
|ElementHandle|textContent|string|Promise<null\|string>|
|ElementHandle|type|void|Promise<void>|
|ElementHandle|uncheck|void|Promise<void>|
|ElementHandle|waitForElementState|void|Promise<void>|
|ElementHandle|waitForSelector|ElementHandle|Promise<null\|ElementHandle<SVGElement\|HTMLElement>>|

For details on the Why and How, check the overarching issue in https://github.com/grafana/xk6-browser/issues/428.

**Comment by inancgumus** [comment]
FYI: @grafana/k6-browser started the work on the `ElementHandle` documentation.
