### ISSUE TITLE
Migrate Locator APIs to async

### ISSUE THREAD

**Issue by inancgumus** [grafana/xk6-browser#1305]
```[tasklist]
### Tasks
- [ ] #1330
- [ ] #1332
- [ ] https://github.com/grafana/xk6-browser/pull/1370
- [ ] #1371
- [ ] grafana/k6-docs#1591
- [ ] https://github.com/grafana/k6-DefinitelyTyped/pull/46
- [ ] Add release notes
```

---

## What

Migrate the following APIs according to the How section in #428:

| Class | Method | Current k6 Return | PW return |
| ---- | ---- | ---- | ---- |
|Locator|clear|void|Promise<void>|
|Locator|dblclick|void|Promise<void>|
|Locator|check|void|Promise<void>|
|Locator|uncheck|void|Promise<void>|
|Locator|isChecked|boolean|Promise<boolean>|
|Locator|isDisabled|boolean|Promise<boolean>|
|Locator|isEditable|boolean|Promise<boolean>|
|Locator|isEnabled|boolean|Promise<boolean>|
|Locator|isHidden|boolean|Promise<boolean>|
|Locator|isVisible|boolean|Promise<boolean>|
|Locator|fill|void|Promise<void>|
|Locator|focus|void|Promise<void>|
|Locator|getAttribute|string\|null|Promise<null\|string>|
|Locator|innerHTML|string|Promise<string>|
|Locator|innerText|string|Promise<string>|
|Locator|textContent|string|Promise<null\|string>|
|Locator|inputValue|string|Promise<string>|
|Locator|selectOption|string[]|Promise<Array<string>>|
|Locator|press|void|Promise<void>|
|Locator|type|void|Promise<void>|
|Locator|hover|void|Promise<void>|
|Locator|dispatchEvent|void|Promise<void>|
|Locator|waitFor|void|Promise<void>|

For details on the Why and How, check the overarching issue in #428.
