### ISSUE TITLE
Migrate Page APIs to async

### ISSUE THREAD

**Issue by inancgumus** [grafana/xk6-browser#1307]
```[tasklist]
### Tasks
- [ ] https://github.com/grafana/xk6-browser/pull/1343
- [ ] #1345
- [ ] #1352
- [ ] #1355
- [ ] https://github.com/grafana/xk6-browser/pull/1370
- [ ] #1371
- [ ] grafana/k6-docs#1602
- [ ] https://github.com/grafana/k6-DefinitelyTyped/pull/48
- [ ] Release Notes:
```

---

## What

Migrate the following APIs according to the How section in #428:

| Class | Method | Current k6 Return | PW return |
| ---- | ---- | ---- | ---- |
|Page|$|ElementHandle\|null|Promise<ElementHandle<SVGElement\|HTMLElement>\|null>|
|Page|$$|ElementHandle[]|Promise<ElementHandle<SVGElement\|HTMLElement>[]>|
|Page|bringToFront|void|Promise<void>|
|Page|check|void|Promise<void>|
|Page|close|void|Promise<void>|
|Page|content|string|Promise<string>|
|Page|dblclick|void|Promise<void>|
|Page|dispatchEvent|void|Promise<void>|
|Page|emulateMedia|void|Promise<void>|
|Page|emulateVisionDeficiency|void|not found in Playwright|
|Page|evaluate<R, Arg>|R|Promise<R>|
|Page|evaluateHandle<R, Arg>|JSHandle<R>|Promise<SmartHandle<R>>|
|Page|fill|void|Promise<void>|
|Page|focus|void|Promise<void>|
|Page|getAttribute|null\|string|Promise<null\|string>|
|Page|hover|void|Promise<void>|
|Page|innerHTML|string|Promise<string>|
|Page|innerText|string|Promise<string>|
|Page|inputValue|string|Promise<string>|
|Page|isChecked|boolean|Promise<boolean>|
|Page|isDisabled|boolean|Promise<boolean>|
|Page|isEditable|boolean|Promise<boolean>|
|Page|isEnabled|boolean|Promise<boolean>|
|Page|isHidden|boolean|Promise<boolean>|
|Page|isVisible|boolean|Promise<boolean>|
|Page|on|void|this|
|Page|opener|Page\|null|Promise<null\|Page>|
|Page|press|void|Promise<void>|
|Page|reload|null\|Response|Promise<null\|Response>|
|Page|screenshot|ArrayBuffer|Promise<Buffer>|
|Page|selectOption|string[]|Promise<Array<string>>|
|Page|setContent|void|Promise<void>|
|Page|setExtraHTTPHeaders|void|Promise<void>|
|Page|setInputFiles|void|Promise<void>|
|Page|setViewportSize|void|Promise<void>|
|Page|tap|void|Promise<void>|
|Page|textContent|string|Promise<null\|string>|
|Page|throttleCPU|void|not found in Playwright|
|Page|throttleNetwork|void|not found in Playwright|
|Page|title|string|Promise<string>|
|Page|type|void|Promise<void>|
|Page|uncheck|void|Promise<void>|
|Page|viewportSize|{width:number;height:number;}|null\|{width:number;height:number;}|
|Page|waitForLoadState|void|Promise<void>|
|Page|waitForSelector|ElementHandle|Promise<null\|ElementHandle<SVGElement\|HTMLElement>>|
|Page|waitForTimeout|void|Promise<void>|

For details on the Why and How, check the overarching issue in #428.
