### ISSUE TITLE
Async API Rollout

### ISSUE THREAD

**Issue by inancgumus** [grafana/xk6-browser#1362]
```[tasklist]
### Tasks
- [ ] #1374
- [ ] #1377
- [ ] grafana/k6#3782
- [ ] grafana/k6#3778
- [ ] grafana/k6#3793
- [x] Update k6-docs to use `k6/browser` instead of `k6/browser/experimental` (https://github.com/grafana/k6-docs/pull/1626)
- [x] Release k6-browser v2.0.0 (v1.6.0 due to go mod)
- [ ] grafana/k6-docs#1612
- [ ] grafana/k6-DefinitelyTyped#50
- [x] Update k6-definitelyTyped to also use `k6/browser` in addition to `k6/browser/experimental` @allansson
```
