### ISSUE TITLE
page.goto is partially associated to the wrong navigation span

### ISSUE THREAD

**Issue by ankur22** [grafana/xk6-browser#1413]
### Brief summary

When performing a `page.goto` the span for this API call is longer than the parent span that it is contained within it. In the screenshot the red square is highlighting the navigation and goto spans that are under scrutiny. The orange box within it at the end highlights that the goto span is spilling over the navigation span. This is incorrect behaviour which is causing other issues.

![Image](https://github.com/user-attachments/assets/9e6dddaa-19ec-4268-82cb-c75290aa2c67)

Due to the above issue, we're seeing odd results in the timeline. In the screenshot below, the red highlighted page span shows the key results of navigating and interacting with the page on https://test.k6.io/my_messages.php. The web vital measurement (in orange) is longer than the duration (in yellow). This is occurring because the web vital measurements start during the previous navigation (in blue) on about:blank during the page.goto call.

![Image](https://github.com/user-attachments/assets/5301aa86-05b9-4795-93f1-209d9629110e)

The resolution is to find a better place in the browser code to stop and start the navigation span when using `page.goto`.

### xk6-browser version

v0.53

### OS

NA

### Chrome version

NA

### Steps to reproduce the problem

Run the following script with tracing enabled to see similar tracing results as shown in the description:

```js
import { browser } from 'k6/browser';

export const options = {
  scenarios: {
    ui: {
      executor: 'shared-iterations',
      iterations: 1,
      options: {
        browser: {
          type: 'chromium'
        },
      },
    },
  },
}

export default async function () {
  const page = await browser.newPage();

  await page.goto("http://localhost:81/sleep?t=2");

  await page.screenshot({ path: 'screenshot.png' });

  await page.close();
}
```

### Expected behaviour

1. The `page.goto` span doesn't spill over out of the parent navigation span.
2. The web vital is smaller than the page span it is associated with.

### Actual behaviour

See description for full details.

```[tasklist]
### Tasks
- [ ] https://github.com/grafana/xk6-browser/pull/1414
- [ ] https://github.com/grafana/xk6-browser/pull/1421
- [x] Release notes: https://github.com/grafana/k6/pull/3949/commits/a52892eef86775ef55cd506e7f6c9f61618d20bf
```

**Comment by ankur22** [comment]
There is in fact two different things going on:

1. The page span duration is not started when the new page starts to load.
2. Splitting the navigation portion of the API call (e.g. `page.goto`) into two parts:
    1. the start of the API call;
    2. the actual navigation and end of the API call are placed in the next parent.

In a [POC](https://github.com/grafana/xk6-browser/pull/1414) I've been able to solve both these issues. However, the issue that needs to be solved is 1.
