### ISSUE TITLE
`waitForEvent` on `BrowserContext` is waiting for async support

### ISSUE THREAD

**Issue by ankur22** [grafana/xk6-browser#447]
Tested against: dbede120c63df43995813a847a25b0e66e289592

`waitForEvent` on `BrowserContext` is waiting for async support.
```[tasklist]
### Tasks
- [x] PRs: https://github.com/grafana/xk6-browser/pull/1042, https://github.com/grafana/xk6-browser/pull/1069
- [x] Release notes: https://github.com/grafana/k6/pull/3413
- [x] Docs: https://github.com/grafana/k6-docs/pull/1384
- [x] Type definitions: https://github.com/grafana/k6-DefinitelyTyped/pull/18
```
