### ISSUE TITLE
Match Dblclick with Playwright's behavior

### ISSUE THREAD

**Issue by ankur22** [grafana/xk6-browser#469]
TODO:

[xk6-browser docs](https://k6.io/docs/javascript-api/xk6-browser/locator/dblclick/) imply that this `dblclick` issue is about locators, however, it's the behavior in our extension in general. 

---

Tested against: https://github.com/grafana/xk6-browser/commit/dbede120c63df43995813a847a25b0e66e289592

The method `dblclick` on `locator` only clicks once.

In the below code it works against `localhost:8080`, which is a test server that can be found here with instructions on how to run it locally: https://github.com/ankur22/testserver.

```javascript
import { sleep } from 'k6';
import { chromium } from 'k6/x/browser';

export default function () {
  const browser = chromium.launch({
    headless: false,
  });
  const context = browser.newContext();
  const page = context.newPage();
  const res = page.goto('https://test.k6.io/browser.php');
  const l = page.locator('#counter-button');
  sleep(1);
  l.dblclick();

  sleep(10);
  browser.close();
}
```

I was expecting the counter on this test page to go up to `2` but it only went up to `1`. When testing with PW i was able to get the expected count of `2`.
```[tasklist]
### Tasks
- [x] FIx issue -- https://github.com/grafana/xk6-browser/pull/1121
- [x] Add to release notes -- https://github.com/grafana/k6/pull/3506
- [x] Docs update -- https://github.com/grafana/k6-docs/pull/1456
```

**Comment by imiric** [comment]
Nice catch!

It doesn't seem related to `Locator`, but to `ElementHandle`:

https://github.com/grafana/xk6-browser/blob/dbede120c63df43995813a847a25b0e66e289592/common/element_handle.go#L242-L244

It should call `Mouse.dblClick()` :smile:

**Comment by inancgumus** [comment]
@ankur22 Nice catch 🏉 @imiric No, it's not because of not calling `dblClick`. Because some locator tests are incorrect 🥲 I'll send a PR.

**Comment by inancgumus** [comment]
@ankur22 Thanks Ankur for helping me find the problems in the locator tests 🙇 

@imiric No, it's not because of not calling `Mouse.dblClick`. Because some locator tests are incorrect 🤦 I'll send a PR.

**Update:**
Ankur, we can double-click. The test server starts the counter from zero. So we see 1 instead of 2 in the k6 logs.

https://github.com/ankur22/testserver/blob/d7e63fd17b0c0b325b55117855e3723019bd532e/main.go#L200-L206

```shell
# output
➜  xk6-browser git:(main) ✗ kbr ../tests/issue469.js
INFO[0002] 0                                             source=browser-console-api
INFO[0002] 1                                             source=browser-console-api
```

But, I know that you were referring to the server's UI. So shouldn't the server needs to listen for the `dblclick` event [here](https://github.com/ankur22/testserver/blob/d7e63fd17b0c0b325b55117855e3723019bd532e/main.go#L244-L245) instead of the `click` event?

I've changed it to `dblclick` and it worked 🥳

**Comment by inancgumus** [comment]
@ankur22 Thanks Ankur for helping me find the problems in the locator tests 🙇 

@imiric No, it's not because of not calling `Mouse.dblClick`. Because some locator tests are incorrect 🤦 I'll send a PR.

**Update:**
Ankur, shouldn't the server needs to listen for the `dblclick` event [here](https://github.com/ankur22/testserver/blob/d7e63fd17b0c0b325b55117855e3723019bd532e/main.go#L244-L245) instead of the `click` event?

I've changed it to `dblclick` and it worked.

**Comment by inancgumus** [comment]
Calling `l.dblclick` works when you change [this](https://github.com/ankur22/testserver/blob/d7e63fd17b0c0b325b55117855e3723019bd532e/main.go#L244-L245) to the following (`ondblclick` instead of `click`):

```html
<td><button type="button" id="counter-button" ondblclick="incrementCounter()">Increment</button></td>
```

After the change, `l.click` doesn't work (as expected). So this might confirm that we can double-click on an element that listens for the double-click events (_irrelevant of whether PW increments the counter twice or not_).

**Comment by inancgumus** [comment]
If we care how PW behaves (I think we might :)), there is a problem because the counter only gets incremented once instead of twice. I found out that there is a slight deviation in our implementation from PW. I'll send a fix for this as well, then.
