### ISSUE TITLE
Implement Web Vitals

### ISSUE THREAD

**Issue by ankur22** [grafana/xk6-browser#693]
This follows on from the POC https://github.com/grafana/xk6-browser/pull/657.

We want to implement the Web Vitals properly into xk6-browser. The following are the sub issues for this issue:

- [x] https://github.com/grafana/xk6-browser/issues/690 (MUST) — v0.9.0
- [x] https://github.com/grafana/xk6-browser/issues/837 (MUST) — v0.9.0
- [x] https://github.com/grafana/xk6-browser/issues/831 (MUST) — v0.9.0

**Comment by ankur22** [comment]
Moving this back to the backlog for now. The must have tasks have been completed.
