### ISSUE TITLE
Investigate working with `new` type for `headless` option

### ISSUE THREAD

**Issue by ankur22** [grafana/xk6-browser#948]
### Feature Description

Since [Chrome 112 there's now a new headless mode](https://developer.chrome.com/articles/new-headless/) which can be enabled with `headless=new` instead of `headless=true`. When using `headless=true` it falls back to the legacy way.

The difference is that with the legacy way, there are two implementation of the chrome, one for headful and one headless, which means that the behaviour of the two sometimes don't match. With the new implementation, the two have been merged into one, which should mean that the behaviour of a test in headful should match the behaviour when `headless=new`.

I ran a very quick experiment, where unfortunately the integration tests hung (deadlock?) so we need to investigate this properly before enabling it.

### Suggested Solution (optional)

Add a new `headless=new` option.

### Already existing or connected issues / PRs (optional)

#1388

```[tasklist]
### Tasks
- [ ] Experiment with `headless=new`
- [ ] Provide compatibility with `headless=true`
- [ ] Test on staging
- [ ] k6 docs
- [ ] k6 release notes and tasks
```

**Comment by inancgumus** [comment]
👍 

> Because Headless was a separate implementation, it had its own bugs and features that weren’t present in headful Chrome. This created a confusing situation where any automated browser test might pass in headful mode but fail in Headless mode, or vice versa — a major pain point for automation engineers. It also excluded any automated testing that relied on having a browser extension installed, for example. The same goes for any other browser-level functionality: unless Headless had its own, separate implementation of it, it wasn’t supported.

**Comment by inancgumus** [comment]
Also important because:

> From: https://developer.chrome.com/docs/chromium/headless
> Note: We intend to remove the old Headless from the Chrome binary and stop supporting this mode in Puppeteer in 2024. Simultaneously, we'll make old Headless mode available as a standalone binary for users who can't upgrade yet.

**Comment by inancgumus** [comment]
> From: https://developer.chrome.com/blog/chrome-headless-shell
>
> There's a trade-off between performance and authenticity.  
>
> * The old Headless mode is a lightweight wrapper around Chromium's //content module, and it therefore has substantially fewer dependencies. Specifically, it does not require X11/Wayland, D-Bus, and is in some ways more performant than the fully-fledged Chrome browser. This makes it suitable for use cases such as automated screenshotting or web scraping.
> * New Headless on the other hand is the real Chrome browser, and is thus more authentic, reliable, and offers more features. This makes it more suitable for high-accuracy end-to-end web app testing or browser extension testing.

![Image](https://github.com/user-attachments/assets/061fadff-7931-4cd7-9472-25dd3dd86e9a)

**Comment by inancgumus** [comment]
The new headless mode [implementation](https://source.chromium.org/chromium/chromium/src/+/ff5efbff97142bbf09194aac1542b88b44599d52:chrome/browser/headless/headless_mode_util.cc;l=31-57;drc=d59bf94449794ed5eed7ba9524657cbaa6b29c2b;bpv=1;bpt=0
):

```cpp
namespace headless {

namespace {
const char kNewHeadlessModeSwitchValue[] = "new";
const char kOldHeadlessModeSwitchValue[] = "old";

enum HeadlessMode {
  kNoHeadlessMode,
  kOldHeadlessMode,
  kNewHeadlessMode,
  kDefaultHeadlessMode = kNewHeadlessMode
};

HeadlessMode GetHeadlessMode() {
  base::CommandLine* command_line = base::CommandLine::ForCurrentProcess();
  if (!command_line->HasSwitch(switches::kHeadless))
    return kNoHeadlessMode;

  std::string switch_value =
      command_line->GetSwitchValueASCII(switches::kHeadless);
  if (switch_value == kOldHeadlessModeSwitchValue)
    return kOldHeadlessMode;
  if (switch_value == kNewHeadlessModeSwitchValue)
    return kNewHeadlessMode;

  return kDefaultHeadlessMode;
}
```

**Comment by inancgumus** [comment]
# Resolution

Using `headless=new` is _optional_ as the `headless` argument (_without a value_) automatically turns on the *new* headless mode above Chromium 112 (see [this](https://source.chromium.org/chromium/chromium/src/+/b9b39a430f71c710d16aafcc67278ef77440c18d)). Users need to use `headless=old` to use a separate Chromium engine as before. So, we don't need to do anything as our cloud Chromium is above 112. For the `headless=old` support, we'd wait until someone explicitly asks for this to keep things simple. Closing this issue now.
