### ISSUE TITLE
Update type definitions with browser and browserContext classes

### ISSUE THREAD

**Issue by ankur22** [grafana/xk6-browser#955]
Update the type definitions to reflect the changes that have been made in #925.
```[tasklist]
### Tasks
- [x] Changes in `browserContext`
- [x] Changes in `browser`
- [x] Removal of `browserType`
- [x] Changes in types that reference either of three classes
```

**Comment by ankur22** [comment]
PR: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/65902

**Comment by inancgumus** [comment]
@ankur22 Close?
