### ISSUE TITLE
Fix e2e & test CI workflows

### ISSUE THREAD

**Issue by ankur22** [grafana/xk6-browser#963]
This issue is related to the issue with chromium crashing in the test ci workflow. We opened an [issue](https://github.com/actions/runner-images/issues/7797) with github and they opened an [issue](https://bugs.chromium.org/p/chromium/issues/detail?id=1458834) with the chrome team.

In addition to the above, github runner images have both chromium and chrome installed. The browser module defaults to working with chromium over chrome on linux machines. The version of chromium on the github runner images doesn't have the fix to prevent it from crashing, but the version of chrome is up to date.

There are several things to resolve with the workflows:

1. The `test` workflow should work with `ubuntu-latest`.
2. The exec path for chrome should be set to `/usr/bin/google-chrome` on linux runners.
3. The `e2e` workflow should work with `ubuntu-latest`.
4. Use the matrix in the `e2e` tests. It's defined but then never used.
5. Remove the install/setup step for linux runners in the `test` workflow.
6. Fix any tests that are failing consistently:
    1. The `TestBrowserRegistry` are very [flakey](https://github.com/grafana/xk6-browser/actions/runs/5488154958/jobs/10000598506).
    2. The `hosts.js` example is [failing](https://github.com/grafana/xk6-browser/actions/runs/5488154952/jobs/10000598049) on Windows.

A [PR](https://github.com/grafana/xk6-browser/pull/962) with most to these changes has already been created. What remains are the fixes for the failing (flakey) tests.
```[tasklist]
### Tasks
- [x] The test workflow should work with ubuntu-latest.
- [x] The exec path for chrome should be set to /usr/bin/google-chrome on linux runners.
- [x] The e2e workflow should work with ubuntu-latest.
- [x] Use the matrix in the e2e tests. It's defined but then never used.
- [x] Remove the install/setup step for linux runners in the test workflow.
- [x] Fix any tests that are failing consistently.
```
