### ISSUE TITLE
elementHandle.isVisible should return straight away even if the selector was not found

### ISSUE THREAD

**Issue by ankur22** [grafana/xk6-browser#981]
### Brief summary

Currently when we work with `elementHandle.isVisible` it will wait and try to match on the given selector before returning `true` or `false` on whether it is visible or not. To match Playwrights behaviour, and the expectations of our users, we should change the behaviour to return straight away even if the selector is not present in the DOM.

```js
  await page.goto(`url-redacted`)

  const alreadyInstalled = await page.locator('//h3[text()="Resource consumption"]').isVisible()

  if (alreadyInstalled) {
    console.log('Dashboards and alert rules already installed on the page')
    return
  }
```

### xk6-browser version

v0.45.0

### OS

NA

### Chrome version

NA

### Docker version and image (if applicable)

NA

### Steps to reproduce the problem

1. Work with `elementHandle.isVisible` and set the selector to something that will not be present on the page that the test navigates to.

### Expected behaviour

It should return `false` straight away.

### Actual behaviour

It waits for the selector to match, but eventually times out.
```[tasklist]
### Tasks
- [x] Use `force` and `noWaitAfter` in `frame.newAction` -- https://github.com/grafana/xk6-browser/pull/1102
- [x] Add 1102 to release notes -- https://github.com/grafana/k6/pull/3465
- [x] Refactor query to allow strict mode -- https://github.com/grafana/xk6-browser/pull/1107
- [x] Implement the fix -- https://github.com/grafana/xk6-browser/pull/1108
- [x] Fix the checks for other APIs that shouldn't wait -- https://github.com/grafana/xk6-browser/pull/1109 & https://github.com/grafana/xk6-browser/pull/1110
- [x] Remove timeout option since the API will not wait for the selector -- https://github.com/grafana/xk6-browser/pull/1111
- [x] Add it to the release notes -- https://github.com/grafana/k6/pull/3506
- [x] Update the type definitions -- https://github.com/grafana/k6-DefinitelyTyped/pull/23
- [x] Update the documentation -- https://github.com/grafana/k6-docs/pull/1457
```
